#!/bin/bash
#=================================================================================
# Copyright (C) Kross1de. All rights reserved.
#=================================================================================

# clear view of what's goin on
clear

# default CPUs amount: 2
SMP="${1}"
if [ -z "${SMP}" ]; then SMP="2"; fi

# default Memory size: 64 MiB
MEM="${2}"
if [ -z "${MEM}" ]; then MEM="64"; fi

qemu-system-x86_64				\
	--enable-kvm				\
	-cpu max				\
	-smp ${SMP}				\
	-m ${MEM}				\
	-cdrom build/coral_os.iso		\
	-rtc base=localtime			\
